### ISSUE TITLE
Zoom-dependent icon sizes

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts-vision-zero#53]
So we can show smaller icons when the map first loads, and larger ones at neighborhood scale.

**Comment by fitnr** [comment]
This would be an excellent way to clean up the map a little

**Comment by fkh** [comment]
@fitnr small icons now show at zoom < 14, then larger ones after that. At really close zooms, we could switch to showing the actual stickers, we'll see how that looks.

We still need to give the icons a tweak to make them better show up against the dark background.

**Comment by fitnr** [comment]
The smaller icons look good. Switching to the actual stickers would probably work on the 3 biggest zooms.

**Comment by fkh** [comment]
Updated with hi-contrast icons and stickers at closer range. Plus, improved "focus" icon.

**Comment by fitnr** [comment]
@fkh It's confusing for the icon style to switch from colored-outline to colored-center. I prefer colored-center because, without a buffer, the many icon colors create a muddy effect. Can you send comps before making this kind of change?

**Comment by fkh** [comment]
@fitnr you are likely seeing locally-cached icons, the new icons are colored-outline small (hi zooms) and large (mid zooms), and then stickers (close zooms). We aren't using color-center at any scale now.

We switched to putting the color on the outside, to avoid seeing all white border when zoomed out.  We can switch back if you prefer it the other way around.

Noted on pushing to staging first.

**Comment by andycochran** [comment]
There are some nice things about the color being on the border of the dots instead of the center… 

When places slightly overlap, you can still see their colors. Previously you saw only the white border. As Frank mentions, this is especially apparent when zoomed all the way out and the old dots created a sea of indistinguishable white borders. But this is also important when zoomed in close and places overlap. 

The new dots also have consistency between the color of the illustration (white/black) and the color of the inside of the dots. And this allows all the dots to be more noticeable—e.g. yellow dot with a white border had no contrast.

**Comment by andycochran** [comment]
Oh, Frank was right about the cache issue. I've renamed the new icons to avoid them being cached. If you view the staging site you'll see the dots as intended.
